/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drinking_water_vending_machine_theeranat;

/**
 *
 * @author uSeR
 */
public class change extends javax.swing.JFrame {

    /**
     * Creates new form change
     */
    int cal_total_price;
    
    public change() {
        initComponents();
    }
    public change(int get_cal_total_price) {
        initComponents();
        cal_total_price = get_cal_total_price;
        int[] B_and_c_change = {100, 50, 20, 10, 5, 2, 1};
        for (int B_and_c : B_and_c_change) {
            if (B_and_c == 100) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_bank100.setEnabled(true);
                    txt_bank100.setEnabled(true);
                    txt_bank100.setText(num_bills + " : " + "bank");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
            else if (B_and_c == 50) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_bank50.setEnabled(true);
                    txt_bank50.setEnabled(true);
                    txt_bank50.setText(num_bills + " : " + "bank");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
            else if (B_and_c == 20) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_bank20.setEnabled(true);
                    txt_bank20.setEnabled(true);
                    txt_bank20.setText(num_bills + " : " + "bank");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
            else if (B_and_c == 10) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_coin10.setEnabled(true);
                    txt_coin10.setEnabled(true);
                    txt_coin10.setText(num_bills + " : " + "coin");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
            else if (B_and_c == 5) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_coin5.setEnabled(true);
                    txt_coin5.setEnabled(true);
                    txt_coin5.setText(num_bills + " : " + "coin");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
            else if (B_and_c == 2) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_coin2.setEnabled(true);
                    txt_coin2.setEnabled(true);
                    txt_coin2.setText(num_bills + " : " + "coin");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
            else if (B_and_c == 1) {
                if (cal_total_price >= B_and_c) {
                    int num_bills = cal_total_price / B_and_c;
                    lb_coin1.setEnabled(true);
                    txt_coin1.setEnabled(true);
                    txt_coin1.setText(num_bills + " : " + "coin");
                    cal_total_price %= B_and_c * num_bills;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lb_bank100 = new javax.swing.JLabel();
        lb_bank50 = new javax.swing.JLabel();
        lb_bank20 = new javax.swing.JLabel();
        lb_coin10 = new javax.swing.JLabel();
        lb_coin5 = new javax.swing.JLabel();
        lb_coin2 = new javax.swing.JLabel();
        lb_coin1 = new javax.swing.JLabel();
        txt_bank100 = new javax.swing.JTextField();
        txt_bank50 = new javax.swing.JTextField();
        txt_bank20 = new javax.swing.JTextField();
        txt_coin10 = new javax.swing.JTextField();
        txt_coin5 = new javax.swing.JTextField();
        txt_coin2 = new javax.swing.JTextField();
        txt_coin1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bank100.png"))); // NOI18N

        jTextField6.setColumns(10);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Your change!");

        lb_bank100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bank100.png"))); // NOI18N
        lb_bank100.setEnabled(false);

        lb_bank50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bank50.png"))); // NOI18N
        lb_bank50.setEnabled(false);

        lb_bank20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bank20.png"))); // NOI18N
        lb_bank20.setEnabled(false);

        lb_coin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/coin10.png"))); // NOI18N
        lb_coin10.setEnabled(false);

        lb_coin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drinking_water_vending_machine_theeranat/coin5.png"))); // NOI18N
        lb_coin5.setEnabled(false);

        lb_coin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/coin2.png"))); // NOI18N
        lb_coin2.setEnabled(false);

        lb_coin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/coin1.png"))); // NOI18N
        lb_coin1.setEnabled(false);

        txt_bank100.setColumns(8);
        txt_bank100.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_bank100.setEnabled(false);

        txt_bank50.setColumns(8);
        txt_bank50.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_bank50.setEnabled(false);

        txt_bank20.setColumns(8);
        txt_bank20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_bank20.setEnabled(false);

        txt_coin10.setColumns(8);
        txt_coin10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_coin10.setEnabled(false);

        txt_coin5.setColumns(8);
        txt_coin5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_coin5.setEnabled(false);

        txt_coin2.setColumns(8);
        txt_coin2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_coin2.setEnabled(false);

        txt_coin1.setColumns(8);
        txt_coin1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_coin1.setEnabled(false);

        jButton1.setText("OK!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_coin1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_coin2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_coin5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_coin10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_bank20, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_bank50, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_bank100, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bank50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bank100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bank20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_coin10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_coin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_coin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_coin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_bank100, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txt_bank100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_bank50, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txt_bank50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_bank20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txt_bank20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_coin10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txt_coin10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_coin5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txt_coin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_coin2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txt_coin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_coin1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txt_coin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_bank100.setText("");
        txt_bank50.setText("");
        txt_bank20.setText("");
        txt_coin10.setText("");
        txt_coin5.setText("");
        txt_coin2.setText("");
        txt_coin1.setText("");
        this.dispose();
        main get_main = new main();
        get_main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lb_bank100;
    private javax.swing.JLabel lb_bank20;
    private javax.swing.JLabel lb_bank50;
    private javax.swing.JLabel lb_coin1;
    private javax.swing.JLabel lb_coin10;
    private javax.swing.JLabel lb_coin2;
    private javax.swing.JLabel lb_coin5;
    private javax.swing.JTextField txt_bank100;
    private javax.swing.JTextField txt_bank20;
    private javax.swing.JTextField txt_bank50;
    private javax.swing.JTextField txt_coin1;
    private javax.swing.JTextField txt_coin10;
    private javax.swing.JTextField txt_coin2;
    private javax.swing.JTextField txt_coin5;
    // End of variables declaration//GEN-END:variables
}
