/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drinking_water_vending_machine_theeranat;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author uSeR
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    
    public main() {
        initComponents();
//        try {
//            FileInputStream fis = new FileInputStream("D:\\Drinking_water_vending_machine_Theeranat\\src\\drinking_water_vending_machine_theeranat\\drinks_data.txt");
//            BufferedReader br = new BufferedReader(new InputStreamReader(fis));
//            String line;
//            while ((line = br.readLine()) != null) {
//                String[] parts = line.split(" ");
//                if (parts.length >= 2 && parts[1].equals("0")) {
//                    
//                }
//            }
//            br.close();
//        } catch (IOException | NumberFormatException e) {
//            e.printStackTrace();
//        }
    }
    String drink_name,drink_pic = "";int drink_value,drink_price,total_price;
    public main(String get_name, int get_value, String get_pic, int get_price, int get_totalprice) {
        initComponents();
        drink_name = get_name;
        drink_value = get_value;
        drink_pic = get_pic;
        drink_price = get_price;
        total_price = get_totalprice;
        jLabel3.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_reset_drinks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/drinksmenu.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/put_money.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Get_a_drink.png"))); // NOI18N
        jLabel3.setEnabled(false);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        btn_reset_drinks.setText("Admin");
        btn_reset_drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset_drinksActionPerformed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reset_drinks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(btn_reset_drinks)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        inputmoney input_money = new inputmoney();
        input_money.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        drinks get_drinks = new drinks();
        get_drinks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

//    StringBuilder use_total_price = new StringBuilder();
    int drink_calallsell,d_price,quantity;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (jLabel3.isEnabled()) {
            String fileName = "D:\\Drinking_water_vending_machine_Theeranat\\src\\drinking_water_vending_machine_theeranat\\drinks_data.txt";
            String filesell = "D:\\Drinking_water_vending_machine_Theeranat\\src\\drinking_water_vending_machine_theeranat\\drinks_sell.txt";
            StringBuilder fileContent = new StringBuilder();
            StringBuilder updatedContent = new StringBuilder();
            try {
                BufferedReader reader = new BufferedReader(new FileReader(fileName));
                String line;
                while ((line = reader.readLine()) != null) {
                    fileContent.append(line).append("\n");
                }
                reader.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "eroor!: " + e.getMessage());
            }
            String newData = fileContent.toString().replaceAll(drink_name+" "+"\\d+", drink_name +" "+ drink_value);
            total_price = total_price - drink_price;
            int cal_total_price = total_price;
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(fileName));
                writer.write(newData);
                writer.close();
                ImageIcon icon = new ImageIcon(drink_pic);
                JOptionPane.showMessageDialog(this, "You get it!","success!",JOptionPane.INFORMATION_MESSAGE, icon);
//                this.dispose();
//                new change(cal_total_price).setVisible(true);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "eroor!: " + e.getMessage());
            }
            try (BufferedReader reader = new BufferedReader(new FileReader(filesell))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    updatedContent.append(line).append("\n");
                    String[] parts = line.split(" ");
                    if (parts[0].equals(drink_name)) {
                        d_price = Integer.parseInt(parts[1]);
                        quantity = Integer.parseInt(parts[2])+1;
                        drink_calallsell = d_price * quantity;
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "eroor!: " + e.getMessage());
            }
            String sellData = updatedContent.toString().replaceAll(drink_name+" "+"\\d+"+" "+"\\d+"+" "+"\\d+", drink_name + " " + d_price + " " + quantity + " " + drink_calallsell);
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(filesell));
                writer.write(sellData);
                writer.close();
                this.dispose();
                new change(cal_total_price).setVisible(true);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "eroor!: " + e.getMessage());
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Please buy drinks!");
            drinks get_drinks = new drinks();
            get_drinks.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_reset_drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset_drinksActionPerformed
        // TODO add your handling code here:
        login get_login = new login();
        get_login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reset_drinksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        easter_egg get_easter_egg = new easter_egg();
        get_easter_egg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset_drinks;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
