/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drinking_water_vending_machine_theeranat;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author uSeR
 */
public class reset_drinks extends javax.swing.JFrame {

    /**
     * Creates new form reset_drinks
     */
    public reset_drinks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_reset = new javax.swing.JButton();
        btn_fill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_reset.setText("Open and fill");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_fill.setText("close");
        btn_fill.setEnabled(false);
        btn_fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_reset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_fill)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn_reset)
                .addGap(34, 34, 34)
                .addComponent(btn_fill)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        String filePath = "D:\\Drinking_water_vending_machine_Theeranat\\src\\drinking_water_vending_machine_theeranat\\drinks_data.txt";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write(" ");
            JOptionPane.showMessageDialog(this, "Open and fill succeed!");
            
            bw.close();
            fw.close();
            btn_fill.setEnabled(true);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_fillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fillActionPerformed
        // TODO add your handling code here:
        String filePath = "D:\\Drinking_water_vending_machine_Theeranat\\src\\drinking_water_vending_machine_theeranat\\drinks_data.txt";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write("water1 20\n");
            bw.write("water2 20\n");
            bw.write("water3 20\n");
            bw.write("water4 20\n");
            bw.write("sponsor 20\n");
            bw.write("bigtea1 20\n");
            bw.write("bigtea2 20\n");
            bw.write("schweppes1 20\n");
            bw.write("singha 20\n");
            bw.write("coconut 20\n");
            bw.write("cvittorange 20\n");
            bw.write("cvittlemon 20\n");
            bw.write("nescafeespresso 20\n");
            bw.write("nescafelatte 20\n");
            bw.write("birdyrobusta 20\n");
            bw.write("schweppes2 20\n");
            bw.write("cokenosugar1 20\n");
            bw.write("cokenosugar2 20\n");
            bw.write("cvittpeach 20\n");
            bw.write("grassjelly 20\n");
            bw.write("cokeoriginal1 20\n");
            bw.write("cokeoriginal2 20\n");
            bw.write("pepsi1 20\n");
            bw.write("pepsi2 20\n");
            bw.write("m150_y1 20\n");
            bw.write("m150_y2 20\n");
            bw.write("m150_b1 20\n");
            bw.write("m150_b2 20\n");
            bw.write("carabao1 20\n");
            bw.write("carabao2 20\n");
            bw.write("volt1 20\n");
            bw.write("volt2 20\n");
            bw.write("mjoygrape 20\n");
            bw.write("mjoylychee 20\n");
            bw.write("birdyespresso 20\n");
            bw.write("jellychake 20");
            JOptionPane.showMessageDialog(this, "close succeed!");
            
            bw.close();
            fw.close();
            admin_use get_admin = new admin_use();
            get_admin.setVisible(true);
            this.dispose();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_fillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset_drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset_drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset_drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset_drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset_drinks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fill;
    private javax.swing.JButton btn_reset;
    // End of variables declaration//GEN-END:variables
}
